on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: fred
        uses: veghead/action-ssh-agent@v1.0.1
        with:
          ssh-private-key: |
            key1
            key2

